name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt
      - run: cargo fmt --all --check
      - run: cargo test --workspace
      - run: cargo clippy --workspace --all-targets -- -D warnings
      - run: cargo package -p deko-dksh
      - run: cargo package -p deko-bitview
      - run: cargo package -p deko-nak --list
      - run: cargo package -p deko-compiler-utils
      - run: cargo package -p deko-shader-compiler-macros
